export enum ActionType {
  LOGOUT = "LOGOUT",
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL = "USER_LOGIN_FAIL",
  SEARCH_QUERY = "SEARCH_QUERY",
  ADD_TO_CART = "ADD_TO_CART",
  SET_VISIBLE = "SET_VISIBLE",
  COD = "COD",
  COUPON_APPLIED = "COUPON_APPLIED",
}
