export enum ActionType {
  LOGOUT = "LOGOUT",
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  SET_USER_DETAILS = "SET_USER_DETAILS",
  USER_REGISTER_FAIL = "USER_REGISTER_FAIL",
  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS",
  USER_LOGIN_FAIL = "USER_LOGIN_FAIL",
  OPEN_ALERT_MESSAGE = "OPEN_ALERT_MESSAGE",
  CLOSE_ALERT_MESSAGE = "CLOSE_ALERT_MESSAGE",
}
