export enum ActionType {
  LOGOUT = "LOGOUT",
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  SET_USER_DETAILS = "SET_USER_DETAILS",
  USER_REGISTER_FAIL = "USER_REGISTER_FAIL",
  USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS",
  USER_LOGIN_FAIL = "USER_LOGIN_FAIL",
  OPEN_ALERT_MESSAGE = "OPEN_ALERT_MESSAGE",
  CLOSE_ALERT_MESSAGE = "CLOSE_ALERT_MESSAGE",
  SET_FRIENDS = "SET_FRIENDS",
  SET_PENDING_FRIENDS_INVITATIONS = "SET_PENDING_FRIENDS_INVITATIONS",
  SET_ONLINE_USERS = "SET_ONLINE_USERS",
  SET_ACTIVE_CONVERSATION = "SET_ACTIVE_CONVERSATION",
  SET_CHAT_MESSAGES = "SET_CHAT_MESSAGES",
  SET_CHAT_TYPE = "SET_CHAT_TYPE",
}


export enum ChatType {
  PRIVATE = "PRIVATE",
  GROUP = "GROUP",
}